### ISSUE TITLE
Add emergencyBell as option to EquipmentTypes

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#20]
This would allow `EquipmentInfo` and `-Properties` to be used for emergency bell modelling.

**Comment by opyh** [comment]
Thanks! We also thought about this as we found some datasets containing this.

https://github.com/sozialhelden/a11yjson/pull/30 contains this as extra `EmergencyDevice` model for now. This is now modeled from a user’s/guest’s/tenant’s perspective rather than a manufacturer’s or facility manager’s.

For more fancy use cases like IoT emergency facility management, I’d rather rely on work bodies like http://iotschema.org/docs/full.html and similar projects as an implementor.
